server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 5MB

app:
  file:
#    storage-directory: D:\Working\Training\BE\bookteria\file-upload
    storage-directory: file-upload
    prefix-download-url: http://localhost:8888/api/v1/file/media/
