server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookteria_profile
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Zxcqwe098570
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
